### ISSUE TITLE
Add Windows packages

### ISSUE THREAD

**Issue by letmaik** [conda-forge/jasper-feedstock#26]
Currently only macOS and Linux packages are built. It would be great to have Windows packages as well. Was there any complication in the past for not doing it?

**Comment by ocefpaf** [comment]
The expertise to build things on Windows is rare and we have very few people that knows how to do it. But it looks like this latest version has `cmake`, which makes things slightly easier. Do you want to try a PR?

**Comment by letmaik** [comment]
I can't dedicate time to this currently, but I'm happy to test or review.

**Comment by kmilos** [comment]
Actually added in PR #27, but we also need a static build @seanyen, see https://github.com/letmaik/rawpy/pull/104#issuecomment-606480174

**Comment by kmilos** [comment]
Static libs for Windows are no longer required by rawpy, so should be ok to close this now?
